import Head from "next/head";
import Layout from "@/components/Layout";
// import useSWR from "swr";
import Image from "next/image";
import profilePic from "../../public/images/profile/profile.png";
import AnimatedText from "@/components/AnimatedText";
import Link from "next/link";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { LinkArrow } from "@/components/Icon";
import Transition from "@/components/Transition";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  // const { data: visitors } = useSWR("/api/ga", async function (url) {
  //   return fetch(url).then((r) => r.json());
  // });
  return (
    <>
      <Head>
        <title>Suyash Agrahari</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="../../public/images/img.ico" />
      </Head>
      <Transition />
      <main className="flex font-mont items-center text-dark w-full dark:text-light min-h-screen">
        <Layout className="pt-0 md:!pt-16 sm:!pt-8 mb-[8rem]">
          <div className="flex items-center justify-between w-full lg:flex-col ">
            <div className="w-1/2 md:w-full">
              <Image
                src={profilePic}
                alt="Image"
                className="w-[90%] h-auto lg:!hidden md:!inline-block md:!w-full mb-8 "
                priority
                sizes="(max-width:500px) 50vw, (max-width:600px) 50vw, 50vw"
              />
            </div>
            <div className="w-1/2 flex flex-col items-center self-center lg:!w-full lg:text-center ">
              <AnimatedText
                text="Hi, I'm Suyash, web Developer."
                className="!text-6xl !text-left xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl"
              />
              <p className="my-4 text-base  font-medium md:text-sm sm:text-xs">
                As a web developer, I am devoted to Transforming visions into
                reality with elegant front-end development and seamless back-end
                integration.
                {/* As a skilled full-stack developer, I am dedicated to turning
                ideas into innovative web applications. Explore my latest
                projects and articles, showcasing my expertise in React.js and
                web development. */}
              </p>
              <div className="flex items-center self-start mt-2 lg:self-center">
                <Link
                  href="https://drive.google.com/file/d/1_OOpgIxAoJ7DGEf4mjU5Fb42UYBUrSos/view"
                  target={"_blank"}
                  download={true}
                  className="flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark  border-solid border-transparent hover:border-dark border-2 dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light hover:dark:border-light md:p-2 md-px-4 md:text-base "
                >
                  Resume <LinkArrow className={"w-6 ml-1 "} />
                </Link>
                <Link
                  className="ml-4 text-lg font-medium capitalize text-dark underline dark:text-light md:text-base"
                  href="mailto:suyashagrahari73@gmail.com"
                >
                  Contact
                </Link>
              </div>
            </div>
          </div>
        </Layout>
      </main>
    </>
  );
}
